import os
from dotenv import load_dotenv

load_dotenv()

SQLALCHEMY_DATABASE_URL = os.getenv("SQLALCHEMY_DATABASE_URL")
SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")

CHAT_DEFAULT_SYSTEM_PROMPT = os.getenv("CHAT_DEFAULT_SYSTEM_PROMPT")
CHAT_MAX_CONTENT_CHARS = int(os.getenv("CHAT_MAX_CONTENT_CHARS"))
CHAT_MAX_MESSAGES = int(os.getenv("CHAT_MAX_MESSAGES"))

INFERENCE_API_KEY = os.getenv("INFERENCE_API_KEY")
INFERENCE_BASE_URL = os.getenv("INFERENCE_BASE_URL")